### ISSUE TITLE
Special Characters in Names

### ISSUE THREAD

**Issue by Malte-Soeren** [flaghunters/Extra-Flags-for-4chan#267]
This Singaporean said that accents "should work now" when asked about some special spanish n
http://boards.4chan.org/int/thread/60142951/flagtism-thread#p60143344
Does that mean I can use äöü and ß in the names of the german regional flags now?
Sorry that I can't ask in the thread but I'm still banned and my friend with a different ISP is currently unavailable.

**Comment by karakalpak** [comment]
>This Singaporean

Me tbh
And yes you can. 
![image](https://cloud.githubusercontent.com/assets/17495420/15674639/71016e22-2770-11e6-8888-35822cdde9b3.png)

**Comment by Malte-Soeren** [comment]
Ok I'll change the german regionals to the correct names

**Comment by Malte-Soeren** [comment]
[Germany.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/291183/Germany.zip)
Here they are, I hope this way of uploading works

**Comment by flagzzzz** [comment]
Added

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Special characters is a bad idea because it's a slippery slope.
Eventually we might hit some characters which cannot be decoded by some browser or OS.
Also changing now will break flags for people who have set them already and it looks like a lot of people do not know how to change it.
But alas, it's set into motion already so it's too late to change back now.
