### ISSUE TITLE
Can't change flag

### ISSUE THREAD

**Issue by James10898** [flaghunters/Extra-Flags-for-4chan#453]
I accidentally selected a city that I do not live in
I do not want people thinking I live there, because they'll assume I do and start asking questions.
The problem is, I cannot change it until there is an update.
Please have it so I can change my region without an update.

**Comment by karakalpak** [comment]
That's what the back button is for.

**Comment by James10898** [comment]
No no, I mean after I have confirmed the flag (which I accidentally did) it doesnt give anything to change it back.

**Comment by karakalpak** [comment]
And the back button does that? I don't get you.

**Comment by AndrewBelt** [comment]
I don't know what you mean by the "back button" other than the browser's back button which makes 0 sense, because when the setup box is closed I don't see anything. I'm using vimperator and 4chanX which is probably interfering with this script.

The best I could figure out is adding `setup.show();` to the end of the script and refreshing to force the setup box to show.
