### ISSUE TITLE
Need another flag manager.

### ISSUE THREAD

**Issue by WhatIsThisImNotGoodWithComputers** [flaghunters/Extra-Flags-for-4chan#464]
Nee someone to add flags

Requirements:

    Know how to use git
    Know how to add lines to the text files or run the script designed for it in ./php - this should not be a problem if you run OS X or Linux.

For GUI applications I recommend Sourcetree for Windows and git-cola for Linux. They are quite easy to use.

Reminder that no flags will be added until we find someone new or someone comes back from the dead.

**Comment by 3Paracetamol** [comment]
Ill take that opportunity. 
I'd say i'm pretty trusted.
Ive made nearly 350 flags for this script.
Ive made 2 map templates for the imgur page.
Ive made all 3 instructional webms for the main page.
Ive made the cover image for the front page.
Ive made the regional flag hunting script work again and post it every week.
and
Ive been here since February.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
You should have an invite.
