### ISSUE TITLE
England Redux

### ISSUE THREAD

**Issue by BedfordAnon** [flaghunters/Extra-Flags-for-4chan#483]
how deep should this go?

United Kingdom > England > Bedfordshire > Central Bedfordshire > Ampthill
or
United Kingdom > England > Bedfordshire > Central Bedfordshire

only asking because Central Bedfordshire has 60 towns/villages and only a few have flags(coat of arms)

**Comment by BedfordAnon** [comment]
uploading England in a few days

**Comment by 3Paracetamol** [comment]
Leave it at the Second option. Since there will be incomplete folders due to the lack of flags representing the shires.

**Comment by BedfordAnon** [comment]
[England.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/680190/England.zip)

:^)

**Comment by MasterAutismo** [comment]
A lot of these flags are 11x11, I don't know how I feel about adding these since we already have a standard of seal on 16x11, and many of them are flags already in the database. I feel like this is a topic we need to bring into /flag/ to discuss and something we should get the opinion of a lot of English anons about. 

Basically gonna hol up on this issue.

**Comment by MasterAutismo** [comment]
Opened up discussion on /flag/, discussion here is fine too but I prefer it on /flag/.

**Comment by BedfordAnon** [comment]
:^)

**Comment by MasterAutismo** [comment]
Prevailing opinion on /flag/ was for the flags to be 16x11. I'm sorry, but please remake the flags and resubmit another issue. Closing.
