### ISSUE TITLE
Need a new flag manager.

### ISSUE THREAD

**Issue by WhatIsThisImNotGoodWithComputers** [flaghunters/Extra-Flags-for-4chan#493]

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
You need to know how to use git, github and be able to run this script "./generate_flag_list_api2.sh".
Linux / Mac OS X required, if you do not have Linux, you can download VirtualBox and run a virtual image of it.
Otherwise you'll have to update flag lists manually.

**Comment by MasterAutismo** [comment]
I'm disqualified, then. I'm just some pleb who runs Windows, has no knowledge of scripts or code, and just makes flags. Somebody else needs to carry the torch.

**Comment by MasterAutismo** [comment]
Okay, so this really needs some attention. Sort of fucking pissing me off at this point, it's been months and my issues are still sitting there. I can't afford to just sit and wait for Botany Bay to show up, and both Kar and PK (who are the only other people with privileges I'm aware of) don't do anything anymore. 

Whoever has the power to give privileges, I'll take them and just add the flags manually, since I'm damn sure it'll be faster than waiting for people with privileges to show up once every blue moon.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks for stepping up, I'll add you this evening  when I'm back home.

You might have a bad time doing it all manually. 
Running the script to update the flaglists.txt is pretty easy, if you don't have Linux you can download an already installed image from osboxes.org.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Invite sent.

**Comment by MasterAutismo** [comment]
Thanks a bunch, it's going to be a bit of a learning curve but I'll figure it out.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Not much has happened yet, still a lot of open issues.

Anyone else?

**Comment by MasterAutismo** [comment]
I don't understand how to use github, if somebody provides me some sort of tutorial on how all of this works then I can start working on closing issues. I haven't been able to learn since classes are keeping me busy.

Otherwise somebody else with knowledge is going to have to step up.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
There are enough tutorials on git and github and related git tools to find on the web, shouldn't be that hard to learn.
If anyone wants to stick with windows I might even be inclined to create a script for windows to update the .txt files. 

If there's noone by the end of this month I'm going to consider the project abandoned and put the repo into a read-only/archive mode, that means that I will close all current issues and disable the issue tracker - after this nothing can be added or deleted from the repo.

**Comment by MasterAutismo** [comment]
I have to stick with Windows - I'm not capable of learning Linux or of using/running it. If you'd be able to create a script for Windows and just inform me on how to run it to add flag packs with whatever program does that, then I'm more than willing to manage this thing by myself. But I'm not a smart guy - I'll make every attempt possible to learn github over spring break, but if it's not that hard to learn, I don't understand why it's so difficult to just make an video tutorial of closing an issue for future reference (because I won't be here to manage it forever - somebody after me will need to learn). 

And I'm really not sure what closing the repo accomplishes, people still use extra flags - it's just a matter of educating a capable manager. I'm willing to do the work, I just don't know how.

**Comment by MasterAutismo** [comment]
Update: PK recently rewrote the flag_lists to have Windows line endings and I was able to add a flag and close #507 without issue by just manually writing Illinois's list to include Tazewell County. 

I should be able to add flags and start closing issues without error now (although slowly), I'm going to get to it ASAP. The .bat file PK gave to automatically generate doesn't seem to work for me (it opens and closes command prompt), so I'm still requesting PK's help on how to get that working, but in the meantime I'll slowly but surely pick away at it.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Do you have java installed? Version 7 or higher.

**Comment by MasterAutismo** [comment]
I didn't. That was probably the issue, I'm a real moron. I downloaded it, going to run the .bat file again. Most of my computers came with Java pre-installed, so I didn't realize. If you check the current /flag/ thread, you can see my thought process behind the mistake with Virginia. I reverted the flag_list edit, so it's fine. 

Going to give it another go.

**Comment by MasterAutismo** [comment]
Holy shit, it finally worked! Thanks a bunch for dealing with all of my dumb mistakes, I think I can finally manage the repo! Let me sync the Virginia changes and give some flags a test on the /flag/ thread.

**Comment by MasterAutismo** [comment]
Okay, fantastic! I managed to get Virginia updated and it's displaying on 4chan properly. The script seems to work well, however, I have one question. When I ran the script, it changed a ton of flag lists and replaced a bunch of special characters with � (unknown character). I'm not sure why this is, but I didn't commit it to the master branch (it was a large commit, I reverted before committing just the Virginia one) and I'm not dealing with any special characters in the US update, but I'm sure some foreign countries will require it. 

If you could get back to me on this and what the problem might be, I'd appreciate it. I can just pull the current repo as-is to fix my local copy and only update what I'm working on, but I'd have to do it after every commit and that's pretty inefficient. Seriously thanks for working with me and being patient, this seems to be the last hurdle in managing the repo.

**Comment by MasterAutismo** [comment]
I found the issue with the .bat file, it seems to convert these (čăćūųđį) specific characters to the ? unknown character because it shifts the encoding from UTF-8 to ANSI for some reason. 

I managed to get about 1000 US flags in and can close a few issues since the US flags don't have those accents, but the .bat is shifting numerous country's lists (I just didn't upload the lists with broken character and fixed the master list manually). If this problem can be fixed, I'll have the repo running smoothly.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Good find. I will look into it shortly.

**Comment by MasterAutismo** [comment]
Thanks, looking forward to being able to manage this all the way.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Please pull and try the new version.

**Comment by MasterAutismo** [comment]
The good news is that it's not messing up special characters anymore. The bad news is that it isn't breaking the lines for some reason and created this (pic related). 
![hm](https://cloud.githubusercontent.com/assets/18697669/26281524/7769eae6-3dc7-11e7-9bd3-0453948e563d.png)

If we can get the .bat to just break the lines on the list, it should work.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
I had to force the tool to use Unix line endings. 
For Notepad, I'm not sure it can handle Unix line endings, if you want to be able to view the files please try Notepad++.
Otherwise just try to add a flag somewhere, commit the flag_list that goes with it and view it here on the github web page to check if line endings are proper.

**Comment by MasterAutismo** [comment]
Didn't realize it was the line endings that changed, it displayed just fine in Notepad++. 

No character issues anymore and it seems to generate the flag_lists just fine now! The flags in Quebec displayed just fine. Thanks a whole bunch for all of the help and patience, I should be able to properly manage the repo now 100%!

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks for your hard work familia.
