### ISSUE TITLE
Kaliningrad Region flags

### ISSUE THREAD

**Issue by xaaxaaxaa** [flaghunters/Extra-Flags-for-4chan#552]
I made 18 2nd-level flags for Kaliningrad Region, Russia. Now it should contain all flags of districts.
[Kaliningrad Region.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1184651/Kaliningrad.Region.zip)

**Comment by MasterAutismo** [comment]
Please resubmit the flag as anti-aliased versions of themselves. When resizing, select Bicubic interpolation. Examples below. I can't do it because I can't find the source for some of these flags (was able to find a source for these two before I gave up). You have until Saturday to submit the flags before I close this issue.

![bagrationovsk](https://user-images.githubusercontent.com/18697669/28907099-68245244-77ea-11e7-84d5-2adb048e35f4.png)  Bagrationovsk
![baltiysk](https://user-images.githubusercontent.com/18697669/28907100-68279224-77ea-11e7-93d6-2020059bd016.png)   Baltiysk

**Comment by MasterAutismo** [comment]
Left this up longer than I had to. You didn't provide the flags or sources for me to make them, so I'm closing the issue. If you'd like to try again, please re-submit with the proper aliasing.
